# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.1.dev1+gf743a5f.d20230801'
__version_tuple__ = version_tuple = (0, 1, 'dev1', 'gf743a5f.d20230801')
